server:
  port: ${PORT:8888}

spring:

  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_POST:5432}/${PG_DB:srms}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
